easy_admin:
  site_name: Conference Guestbook

  design:
    menu:
      - { route: 'homepage', label: 'Back to website', icon: 'home' }
      - { entity: 'Conference', label: 'Conferences', icon: 'map-marker' }
      - { entity: 'Comments', label: 'Comments', icon: 'comments'}
  
  entities:
    Conference:
      class: App\Entity\Conference
    Comments:
      class: App\Entity\Comment
      list:
        fields:
          - author
          - { property: 'email', type: 'email' }
          - { property: 'createdAt', type: 'datetime' }
        sort: [ 'createdAt', 'ASC' ]
        filters: [ 'conference' ]
      edit:
        fileds:
          - { property: 'conference' }
          - { property: 'createdAt', type: 'datetime', type_options: { attr: { readonly: true }}}
          - author
          - { property: 'email', type: 'email'}
          - text
          